# Generated by Django 4.2.11 on 2026-04-13 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('idioma_preferido', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='crm.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Creacion', 'Creación'), ('Edicion', 'Edición'), ('Eliminacion', 'Eliminación'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='crm.usuario')),
            ],
            options={
                'db_table': 'Log_Auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('Llamada', 'Llamada'), ('Correo', 'Correo'), ('Chat', 'Chat'), ('Reunion', 'Reunión'), ('Otro', 'Otro')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('resultado', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('id_contacto', models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.contacto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='crm.usuario')),
            ],
            options={
                'db_table': 'Interacciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_agente_asignado',
            field=models.ForeignKey(blank=True, db_column='id_agente_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='crm.usuario'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Normal', max_length=10)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_contacto', models.ForeignKey(blank=True, db_column='id_contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='crm.contacto')),
                ('id_usuario_asignado', models.ForeignKey(db_column='id_usuario_asignado', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='crm.usuario')),
            ],
            options={
                'db_table': 'Tareas',
                'ordering': ['fecha_limite'],
                'indexes': [models.Index(fields=['estado'], name='Tareas_estado_23fa52_idx'), models.Index(fields=['fecha_limite'], name='Tareas_fecha_l_f6b6ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('etapa', models.CharField(choices=[('Prospecto', 'Prospecto'), ('Contactado', 'Contactado'), ('Propuesta', 'Propuesta'), ('Negociacion', 'Negociación'), ('Cerrado Ganado', 'Cerrado Ganado'), ('Cerrado Perdido', 'Cerrado Perdido')], default='Prospecto', max_length=50)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('probabilidad_pct', models.PositiveSmallIntegerField(default=0)),
                ('fecha_cierre_est', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_contacto', models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.contacto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='crm.usuario')),
            ],
            options={
                'db_table': 'Oportunidades',
                'indexes': [models.Index(fields=['etapa'], name='Oportunidad_etapa_cba106_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['nombre'], name='Contactos_nombre_ea7dad_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['empresa'], name='Contactos_empresa_7aedf8_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['estado'], name='Contactos_estado_8ab881_idx'),
        ),
    ]
